### ISSUE TITLE
Implement `project` for `Transform`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#264]
See [java implementation](https://github.com/apache/iceberg/blob/d350c9b8c995a2953aa8b80a0a1fc7cadc4dd16a/api/src/main/java/org/apache/iceberg/transforms/Transform.java#L115).

What's project used for? Say we have row filter `a = 10`, and we have a partition spec `bucket(a, 37) as bs`, if one row matches `a=10`, then its partition value should match `bucket(10, 37) as bs`, and we project `a=10` to `bs = bucket(10, 37)`.

Blocked by #283

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
...just to make sure I'm on the right track - and to confirm the idea.

Here is what I would (high-level):
- implement `fn project` on Transform
- match Transform & orginal BoundPredicate
- handle each Transform (e.g. Bucket) and Predicate according to Java Implementation
- return `Option<Predicate>`

In order to implement the `ProjectionEvaluator` later, we can then get the `PartitionSpec` from the manifest, iterate over `fields: Vec<PartitionField>` and call `fn project(...)` on each field's transform...

some pseudo-implementation to illustrate: 
```rust
impl Transform {
// ...
pub fn project(&self, name: String, pred: &BoundPredicate) -> Option<Predicate> {
        match self {
            Transform::Bucket(_) => match pred {
                BoundPredicate::Unary(expr) => Some(Predicate::Unary(UnaryExpression::new(
                    expr.op(),
                    Reference::new(name),
                ))),
                _ => unimplemented!(),
            },
            _ => unimplemented!(),
        }
    }
}
```

```rust
#[test]
fn test_bucket_project() {
    let trans = Transform::Bucket(8);

    let name = "projected_name".to_string();

    let field = NestedField::required(1, "a", Type::Primitive(PrimitiveType::Int));

    let pred = BoundPredicate::Unary(UnaryExpression::new(
        PredicateOperator::IsNull,
        BoundReference::new("original_name", Arc::new(field)),
    ));

    let result = trans.project(name, &pred).unwrap();

    assert_eq!(format!("{result}"), "projected_name IS NULL");
}

```

**Comment by liurenjie1024** [comment]
@marvinlanhenke  Sorry for late reply. Yeah, this is exactly what I'm thinking about, thanks!

**Comment by marvinlanhenke** [comment]
thank you, once #283 is ready, I will continue here.

**Comment by marvinlanhenke** [comment]
@ZENOTME 
are you still working on #287 and the proposed interface? 
just looking for a quick update on this - and huge thanks for your effort on this.

**Comment by ZENOTME** [comment]
> @ZENOTME are you still working on #287 and the proposed interface? just looking for a quick update on this - and huge thanks for your effort on this.

Yes. I will update it later.

**Comment by marvinlanhenke** [comment]
@liurenjie1024 @ZENOTME 
...the `fn project(...)` is getting kinda extensive (lengthy). I think it'd be appropriate to introduce some helper functions here instead of writing a huge `match` statement - to make the code more readable and reduce duplication. 

Any suggestions/ preferences where to put those?

- `mod.rs` in iceberg/src/transform
- create `utils.rs` in iceberg/src/spec
- create a new private struct and impl the helper fns there

? thanks for your thoughts on this

**Comment by liurenjie1024** [comment]
> @liurenjie1024 @ZENOTME ...the `fn project(...)` is getting kinda extensive (lengthy). I think it'd be appropriate to introduce some helper functions here instead of writing a huge `match` statement - to make the code more readable and reduce duplication.
> 
> Any suggestions/ preferences where to put those?
> 
> * `mod.rs` in iceberg/src/transform
> * create `utils.rs` in iceberg/src/spec
> * create fns on impl Transform itself
> 
> thanks for your thoughts on this
> 
> EDIT: For now, I decided to go with option no. 3, which I like since the scope of those helper functions is restricted only to `Transform` - putting those into some `utils.rs` would not be justified, since nobody else woud need those fns...

Hi, @marvinlanhenke Thanks for raising this. I prefer option no. 3 too with similar reason: putting related codes together helps to organize things better.

**Comment by ZENOTME** [comment]
> @liurenjie1024 @ZENOTME ...the `fn project(...)` is getting kinda extensive (lengthy). I think it'd be appropriate to introduce some helper functions here instead of writing a huge `match` statement - to make the code more readable and reduce duplication.
> 
> Any suggestions/ preferences where to put those?
> 
> * `mod.rs` in iceberg/src/transform
> * create `utils.rs` in iceberg/src/spec
> * create fns on impl Transform itself
> 
> thanks for your thoughts on this
> 
> EDIT: For now, I decided to go with option no. 3, which I like since the scope of those helper functions is restricted only to `Transform` - putting those into some `utils.rs` would not be justified, since nobody else woud need those fns...

+1 for no. 3 too
