### ISSUE TITLE
Why shouldn't we return an `UnboundPartitionSpec` instead?

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#694]
I'm not convinced that we need another type, such as `SchemalessPartitionSpec`. Why shouldn't we return an `UnboundPartitionSpec` instead? Looking at the signatures:

```rust
pub struct UnboundPartitionSpec {
    /// Identifier for PartitionSpec
    pub(crate) spec_id: Option<i32>,
    /// Details of the partition spec
    pub(crate) fields: Vec<UnboundPartitionField>,
}
```

```rust
pub struct SchemalessPartitionSpec {
    /// Identifier for PartitionSpec
    spec_id: i32,
    /// Details of the partition spec
    fields: Vec<PartitionField>,
}
```

And the `PartitionField` and `UnboundPartitionField` are basically the same.

> Introducing SchemalessPartitionSpec might be our way to avoid https://github.com/apache/iceberg/issues/4563.

If we cannot find the field anymore, the best thing to do is to include the file in the query plan.

_Originally posted by @Fokko in https://github.com/apache/iceberg-rust/pull/645#discussion_r1836605349_

**Comment by Xuanwo** [comment]
Hi, @Fokko, I created an issue to make it easier for us to continue the discussion.

Also cc @liurenjie1024 and @c-thiel.

**Comment by Fokko** [comment]
@Xuanwo Thanks, appreciate it. I'm also preparing a PR for Java that illustrates the solution more clearly.

**Comment by c-thiel** [comment]
I think I have most of my motivation in https://github.com/apache/iceberg-rust/pull/645#issue-2543573501 and the comments referenced above. I follow the argument from Renjie. 
For me `UnboundPartitionSpec` has a different semantic than a previously bound spec, manifested also in the Optional Field ID. Using `UnboundPartitionSpec` in `TableMetadata` would introduce lines of error handling in other places, where we expect the `FieldId` to be present. As `field_id` is a required field in the spec for `TableMetadata`, we would have to use `SchemalessPartitionSpec` at least to deserialize the json before transforming it to `UnboundPartitionSpec`.

**Comment by c-thiel** [comment]
@liurenjie1024, @Fokko, @Xuanwo we should probably come to a conclusion here before the next release.
@Fokko is there already something in your Java PR which we can peek at? What do you have in mind for a solution?

**Comment by Fokko** [comment]
Unbound (not bound to a schema) and schemaless are the same, so I find them confusing. 

Regarding https://github.com/apache/iceberg-rust/pull/645#issue-2543573501 there are some incorrect assumptions there:

> If we agree on this, then we have a small Problem with TableMetadata: It contains historic PartitionSpecs that cannot be bound against the current_schema. As a result, we need a type that has the same properties as PartitionSpec but is not bound to a schema. I thought we could use UnboundPartitionSpec for this at first, but it serves a different purpose and would make the very important `field_id` Optional.

I don't understand this statement. If I look at the `UnboundPartitionSpec`:

```rs
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Clone, TypedBuilder)]
#[serde(rename_all = "kebab-case")]
pub struct UnboundPartitionField {
    /// A source column id from the table’s schema
    pub source_id: i32,
    /// A partition field id that is used to identify a partition field and is unique within a partition spec.
    /// In v2 table metadata, it is unique across all partition specs.
    #[builder(default, setter(strip_option))]
    pub field_id: Option<i32>,
    /// A partition name.
    pub name: String,
    /// A transform that is applied to the source column to produce a partition value.
    pub transform: Transform,
}

/// Unbound partition spec can be built without a schema and later bound to a schema.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Clone, Default)]
#[serde(rename_all = "kebab-case")]
pub struct UnboundPartitionSpec {
    /// Identifier for PartitionSpec
    pub(crate) spec_id: Option<i32>,
    /// Details of the partition spec
    pub(crate) fields: Vec<UnboundPartitionField>,
}
```

> A PartitionSpec is only valid for the schema is had been build against, and we should not imply otherwise.

This is not entirely correct. For example, when a field is being promoted in a valid way, then it is still valid to bind against the same source-id.

So going from the problem space to the solution space. I was looking at the Java code and the PyIceberg code, and at PyIceberg we took a slightly different approach that might be interesting for Iceberg-rust as well. As mentioned earlier, the source ID might evolve (assume compatible ones `int -> long`, `float -> double`, etc) over time. The most obvious example is the identity-partition where the `sourceType` is equal to the `resultType`. Therefore we allow binding with different schema's in PyIceberg: https://github.com/apache/iceberg-python/blob/b2f0a9e5cd7dd548e19cdcdd7f9205f03454369a/pyiceberg/partitioning.py#L203-L225 I think that might be a better approach for Rust as well.

When the field is not in the current spec anymore, it is also unlikely that you would filter on that field, therefore that field from the partition-spec could also be ignored. The downside is that with strongly typed languages, we need to know the type upfront, and otherwise we only know it when we read the actual Avro file (that has the schema with the type). Therefore I'm playing around with a solution for this on the Java side: https://github.com/apache/iceberg/pull/11542

I hope this helps!

**Comment by c-thiel** [comment]
@liurenjie1024, @Xuanwo, @Fokko may I ask for another round of Feedback for this?
I believe if we decide to not introduce a `SchemalessPartitionSpec`, we should do so before `0.4.0`

**Comment by c-thiel** [comment]
@Fokko didn't you try to remove the `buildUnchecked` in Java? Did you succeed?

> Add a crate private buildUnchecked method.

At least for `Lakekeeper` we would need `buildUnchecked` to be public. We are creating TableMetadata not from a big JSON blob, but instead from individual parts that we store in the Database in individual tables. This makes some operations around snapshots lightning fast, because we don't need to do a slow roundtrip to S3. We need the same fine-granular control publicly exposed that the MetadataBuilder is using internally as we would need to stay on a fork otherwise.

Apart from that, my preference would still be to introduce a lightweight additional type that clearly states what its used for than to add a `buildUnchecked` method with lazy accessors that might panic if whoever wrote the Metadata file did not implement the checks accordingly - this includes all java and pyiceberg versions that are currently out.

With `SchemalessPartitionSpec` we already have lazy field types, as we can just `.bind()` it at a later point in time.

**Comment by Fokko** [comment]
I've created https://github.com/apache/iceberg/pull/11604 to reflect my idea on the Java side. When you have `PartitionSpec` that references a field that has been dropped, then we can also drop it from the PartitionSpec, because we will never use it. Another option I'm noodling about, is replacing the type with the newly in V3 introduced `UnknownType`.

> @Fokko didn't you try to remove the `buildUnchecked` in Java? Did you succeed?

If we the PR I mentioned above in, we can remove the `buildUnchecked`. What I think is even better is to defer the binding to a later point like [we did in PyIceberg](https://github.com/apache/iceberg-python/blob/68e17af746021f630b7efa38a50b3ffb51a2dad8/pyiceberg/partitioning.py#L203-L225). This is performance wise probably also better, because you don't know yet which partition spec's you're going to encounter. I checked what the current situation is in PyIceberg, and there we need one similar check: https://github.com/apache/iceberg-python/pull/1393
 The Avro reader will just skip the partition field that references the dropped field.
