### ISSUE TITLE
website: Setup rust.iceberg.apache.org

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#8]
Following the same style as `py.iceberg.apache.org`, we need to create `rust.iceberg.apache.org` to host all documentation related to Rust. My current plan is to host rustdoc, which contains the API documentation for `iceberg-rust`. We can add more content in the future.

The content in `rust.iceberg.apache.org` will be similiar to [opendal](https://opendal.apache.org/docs/rust/opendal/).

cc @Fokko, would you like to help us setup the domain?

---

This issue is not a block, we can address it before the first release.

**Comment by Xuanwo** [comment]
By the way, It's ok for me to have `rs.iceberg.apache.org` for short :smile:

**Comment by Xuanwo** [comment]
> So currently this is an alias of api docs in `docs.rs`?

Yes, host the API docs for `main` branch.

**Comment by Fokko** [comment]
Thanks for raising this. Setting up docs is very easy, you can take the https://github.com/apache/iceberg/blob/master/.github/workflows/python-ci-docs.yml as an example. The important piece here is to have a `CNAME` file in the root of the branch, that has the URL.

Brian Olsen also initiated a thread on the dev-list: https://lists.apache.org/thread/nq283g83p9cgx518jwo7dg85fm5gjrvv Maybe good to jump in there as well, since this will also affect rust at some point.

**Comment by liurenjie1024** [comment]
Duplicated with #114
